import fs from "node:fs";
import path from "node:path";
import { IS_SERVERLESS } from "../config/runtime.js";

const LOCAL_DIR = "uploads";

/**
 * Single place that turns validated upload bytes into a stored, servable
 * reference. Two very different backends sit behind one return value:
 *
 *   local  -> "uploads/<uuid>.webp"        (relative path, served by express.static)
 *   Vercel -> "https://<id>.public.blob..." (absolute URL, served by Blob's CDN)
 *
 * Callers must treat the return value as opaque. `fileUrl()` on both clients
 * passes absolute URLs through untouched, so existing rows holding relative
 * paths keep working alongside new rows holding Blob URLs, with no migration.
 */

async function putBlob(buffer, key, contentType) {
  // Imported lazily so local development and the PM2 deployment never need the
  // package, or a BLOB_READ_WRITE_TOKEN, just to boot.
  const { put } = await import("@vercel/blob");
  const { url } = await put(key, buffer, {
    access: "public",
    contentType,
    // The caller already generated a UUID filename; a second random suffix
    // would make the stored URL impossible to predict from the DB row.
    addRandomSuffix: false,
  });
  return url;
}

async function putLocal(buffer, key) {
  await fs.promises.mkdir(LOCAL_DIR, { recursive: true });
  const dest = path.join(LOCAL_DIR, path.basename(key));
  await fs.promises.writeFile(dest, buffer);
  // Keep POSIX separators: these strings end up in URLs, and path.join emits
  // backslashes on Windows.
  return dest.split(path.sep).join("/");
}

/**
 * Stores already-validated, already-processed bytes and returns the stored
 * reference. This is the only seam the upload middleware writes through, so
 * switching backends never requires touching a route or controller.
 *
 * `path.basename` is applied to the filename so a crafted value cannot escape
 * the intended folder.
 *
 * @param {Buffer} buffer
 * @param {string} filename - secure filename generated by the uploader
 * @param {string} contentType
 * @param {string} folder
 * @returns {Promise<string>} stored reference (relative path or absolute URL)
 */
export async function persistBuffer(buffer, filename, contentType, folder = LOCAL_DIR) {
  const key = `${folder}/${path.basename(filename)}`;
  return IS_SERVERLESS
    ? putBlob(buffer, key, contentType)
    : putLocal(buffer, key);
}

export default { persistBuffer };
