import fs from "node:fs";
import path from "node:path";
import { IS_SERVERLESS } from "../config/runtime.js";

const LOCAL_DIR = "uploads";
const DEFAULT_BUCKET = "gym-uploads";

/**
 * Single place that turns validated upload bytes into a stored, servable
 * reference. Three very different backends sit behind one return value:
 *
 *   Supabase -> "https://<ref>.supabase.co/storage/v1/object/public/..." (absolute URL)
 *   Vercel   -> "https://<id>.public.blob..."                            (absolute URL)
 *   local    -> "uploads/<uuid>.webp"                                    (relative path)
 *
 * Callers must treat the return value as opaque. `fileUrl()` on both clients
 * passes absolute URLs through untouched, so existing rows holding relative
 * paths keep working alongside new rows holding absolute URLs, with no
 * migration and no client change when the backend is switched.
 */

const supabaseConfig = () => {
  const url = (process.env.SUPABASE_URL || "").trim().replace(/\/+$/, "");
  const key = (
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.SUPABASE_SERVICE_KEY ||
    ""
  ).trim();
  if (!url || !key) return null;
  return {
    url,
    key,
    bucket: (process.env.SUPABASE_STORAGE_BUCKET || DEFAULT_BUCKET).trim(),
  };
};

/**
 * Uploads through the Storage REST API rather than @supabase/supabase-js.
 *
 * The SDK exists to give you auth, realtime and PostgREST; none of that is
 * wanted here, and a single authenticated POST avoids adding a dependency (and
 * its cold-start cost) to a function that already boots slowly.
 *
 * The service-role key is required: the bucket is public to READ, but anon
 * clients cannot write to it, which is exactly the split we want - the browser
 * fetches images directly from the CDN, only this server can put them there.
 */
async function putSupabase({ url, key, bucket }, buffer, objectKey, contentType) {
  const endpoint = `${url}/storage/v1/object/${bucket}/${objectKey}`;
  const res = await fetch(endpoint, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${key}`,
      "Content-Type": contentType || "application/octet-stream",
      // The caller already generated a UUID filename, so a collision means a
      // genuine retry of the same upload rather than two different files.
      "x-upsert": "true",
      "cache-control": "public, max-age=31536000, immutable",
    },
    body: buffer,
  });

  if (!res.ok) {
    // Surface Supabase's own message: "Bucket not found" and "new row violates
    // row-level security policy" are the two failures worth telling apart, and
    // a bare status code hides both.
    const detail = await res.text().catch(() => "");
    throw new Error(
      `Supabase storage upload failed (${res.status}): ${detail.slice(0, 300)}`,
    );
  }

  return `${url}/storage/v1/object/public/${bucket}/${objectKey}`;
}

async function putBlob(buffer, key, contentType) {
  // Imported lazily so local development and the PM2 deployment never need the
  // package, or a BLOB_READ_WRITE_TOKEN, just to boot.
  const { put } = await import("@vercel/blob");
  const { url } = await put(key, buffer, {
    access: "public",
    contentType,
    // The caller already generated a UUID filename; a second random suffix
    // would make the stored URL impossible to predict from the DB row.
    addRandomSuffix: false,
  });
  return url;
}

async function putLocal(buffer, key) {
  await fs.promises.mkdir(LOCAL_DIR, { recursive: true });
  const dest = path.join(LOCAL_DIR, path.basename(key));
  await fs.promises.writeFile(dest, buffer);
  // Keep POSIX separators: these strings end up in URLs, and path.join emits
  // backslashes on Windows.
  return dest.split(path.sep).join("/");
}

/**
 * Stores already-validated, already-processed bytes and returns the stored
 * reference. This is the only seam the upload middleware writes through, so
 * switching backends never requires touching a route or controller.
 *
 * Supabase wins when it is configured, on purpose and in every environment:
 * the point of pinning storage to one bucket is that a file uploaded from a
 * developer's machine is the same file production serves. Falling back per
 * environment would silently scatter media across three backends again.
 *
 * `path.basename` is applied to the filename so a crafted value cannot escape
 * the intended folder.
 *
 * @param {Buffer} buffer
 * @param {string} filename - secure filename generated by the uploader
 * @param {string} contentType
 * @param {string} folder
 * @returns {Promise<string>} stored reference (relative path or absolute URL)
 */
export async function persistBuffer(buffer, filename, contentType, folder = LOCAL_DIR) {
  const key = `${folder}/${path.basename(filename)}`;

  const supabase = supabaseConfig();
  if (supabase) return putSupabase(supabase, buffer, key, contentType);

  return IS_SERVERLESS
    ? putBlob(buffer, key, contentType)
    : putLocal(buffer, key);
}

export default { persistBuffer };
